safe: true
lsi: false
exclude: ['Gemfile','Gemfile.lock']
permalink: pretty

# utf-8 is default for recent versions of Ruby, but set it anyway
encoding:     "utf-8"
# set markdown extension to be sure
markdown_ext: "md"

gems:
  - jekyll-redirect-from
