
# utf-8 is default for recent versions of Ruby, but set it anyway
encoding:     "utf-8"
# set markdown extension to be sure
markdown_ext: "md"

# Convert links to posts from year-month-data-name.html to name.html
permalink: none